name: PDGHTwitter
main: me.mchiappinam.pdghtwitter.Main
version: 1.0
author: mchiappinam
website: http://pdgh.com.br/ & https://hostload.com.br/
commands:
   tweet:
      description: Info.
      usage: /<command>